<script setup>
import Navbar from "@/Components/Navbar.vue";
import { useForm } from "@inertiajs/vue3";
import { createToaster } from "@meforma/vue-toaster";
import { ref } from "vue";

// 1. Import QuillEditor and its CSS
import { QuillEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css"; // Or use vue-quill.bubble.css

const toaster = createToaster();

const tagInput = ref("");
const tags = ref([]);

const addTag = () => {
    const name = tagInput.value.trim();
    if (name && !tags.value.includes(name)) {
        tags.value.push(name);
    }
    tagInput.value = "";
};

const removeTag = (name) => {
    tags.value = tags.value.filter((t) => t !== name);
};

const form = useForm({
    title: "",
    // content will now hold HTML generated by Quill
    content: "",
    image: null,
    visibility: "public",
    tags: tags.value,
});

function handleFileChange(event) {
    form.image = event.target.files[0];
}

function createPost() {
    form.tags = tags.value;

    // The form.content already contains the HTML from Quill
    form.post("/create-post", {
        forceFormData: true, // Keep if you need file uploads
        onSuccess: () => {
            toaster.success("Post created successfully!");
            // Optionally reset the form, including the editor content
            form.reset();
            tags.value = []; // Reset tags too if needed
            // Quill editor might need explicit reset if form.reset() isn't enough
            // You might need a ref to the editor component to call its methods
        },
        onError: (errors) => {
            toaster.error(
                errors.title || errors.content || "Something went wrong"
            );
        },
    });
}
</script>

<template>
    <Navbar />
    <div class="container mt-5">
        <h2>Create Post</h2>
        <form @submit.prevent="createPost">
            <!-- Title -->
            <div class="mb-3">
                <label>Title</label>
                <input v-model="form.title" class="form-control" />
            </div>

            <!-- Content -->
            <div class="mb-3">
                <label>Content</label>
                <!-- 2. Replace textarea with QuillEditor -->
                <!-- 3. Bind content using v-model:content and set contentType -->
                <QuillEditor
                    v-model:content="form.content"
                    theme="snow"
                    contentType="html"
                    toolbar="essential"
                    style="min-height: 200px"
                />
                <!-- Remove the old textarea:
                <textarea
                    v-model="form.content"
                    class="form-control"
                    rows="5"
                ></textarea>
                -->
            </div>

            <!-- Visibility -->
            <div class="mb-3">
                <label>Visibility</label>
                <select v-model="form.visibility" class="form-control">
                    <option value="public">Public</option>
                    <option value="private">Private</option>
                </select>
            </div>

            <!-- Image -->
            <div class="mb-3">
                <label>Image</label>
                <input
                    type="file"
                    @change="handleFileChange"
                    class="form-control"
                />
            </div>

            <!-- Tags -->
            <div class="mb-3">
                <label>Tags</label>
                <div class="d-flex">
                    <input
                        v-model="tagInput"
                        @keyup.enter.prevent="addTag"
                        placeholder="Type tag and hit Enter"
                        class="form-control me-2"
                    />
                    <button
                        type="button"
                        @click="addTag"
                        class="btn btn-secondary"
                    >
                        Add
                    </button>
                </div>
                <div class="mt-2">
                    <span
                        v-for="tag in tags"
                        :key="tag"
                        class="badge bg-primary me-1"
                    >
                        {{ tag }}
                        <span @click="removeTag(tag)" style="cursor: pointer"
                            >×</span
                        >
                    </span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
            <!-- Added type="submit" -->
        </form>
    </div>
</template>
